language: python
sudo: false
python:
- 2.7
rvm:
  - 2.2.0
addons:
  apt:
    packages:
    - python-lxml
    - python-pip
    
install:
- gem install kramdown-rfc2629
- pip install xml2rfc
- rvm install 2.2.0
- rvm use 2.2.0
- ruby --version
- gem install rake
- gem install cddl
script: 
- xml2rfc draft-ietf-cose-msg.xml -o cose.xml --exp
- rake verify
- make ghpages
